version: "2.2"

services:
  nginx:
    image: nginx
    ports: 
      - 80:80
      - 443:443
      
    volumes:
      - ./html:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-cert/:/etc/ssl/certs
      - ./nginx-key/:/etc/ssl/private
      - ./nginx-logs/:/var/log/nginx/