version: "2.2"

services:
  nginx:
    image: nginx
    ports: 
      - 80:80
      - 443:443
      
    volumes:
      - ./html/:/usr/share/nginx/html/
      - ./nginx-ssl/:/etc/ssl/
      - ./nginx-logs/:/var/log/nginx/
      - ./nginx.conf/:/etc/nginx/conf.d/